// Generated by stratus_hls 21.20-p100  (96289.240513)
// Tue May 30 22:52:21 2023
// from ../SobelFilter.cpp
#ifndef CYNTH_PART_SobelFilter_SobelFilter_RAM_28X32_1_h
#define CYNTH_PART_SobelFilter_SobelFilter_RAM_28X32_1_h

#include "systemc.h"
#include "stratus_hls.h"
/* Include declarations of instantiated parts. */


/* Declaration of the synthesized module. */

struct SobelFilter_RAM_28X32_1 : public sc_module {
  sc_in<sc_uint<32> > DIN;
  sc_in<sc_uint<1> > CE;
  sc_in<sc_uint<1> > RW;
  sc_in<sc_uint<5> > in1;
  sc_out<sc_uint<32> > out1;
  sc_in<bool > clk;
  SobelFilter_RAM_28X32_1( sc_module_name name );
  SC_HAS_PROCESS(SobelFilter_RAM_28X32_1);
  sc_uint<32> mem[28];
  void SobelFilter_RAM_28X32_1_thread_1();
};

#endif
