`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 06:00:56 CST (May 14 2023 22:00:56 UTC)

module SobelFilter_Add_32Sx2U_32S_1(in2, in1, out1);
  input [31:0] in2;
  input [1:0] in1;
  output [31:0] out1;
  wire [31:0] in2;
  wire [1:0] in1;
  wire [31:0] out1;
  wire add_23_2_n_4, add_23_2_n_5, add_23_2_n_8, add_23_2_n_9,
       add_23_2_n_10, add_23_2_n_11, add_23_2_n_12, add_23_2_n_14;
  wire add_23_2_n_15, add_23_2_n_17, add_23_2_n_18, add_23_2_n_20,
       add_23_2_n_21, add_23_2_n_22, add_23_2_n_23, add_23_2_n_24;
  wire add_23_2_n_25, add_23_2_n_26, add_23_2_n_27, add_23_2_n_28,
       add_23_2_n_29, add_23_2_n_30, add_23_2_n_31, add_23_2_n_32;
  wire add_23_2_n_34, add_23_2_n_35, add_23_2_n_36, add_23_2_n_37,
       add_23_2_n_38, add_23_2_n_40, add_23_2_n_41, add_23_2_n_42;
  wire add_23_2_n_43, add_23_2_n_44, add_23_2_n_45, add_23_2_n_46,
       add_23_2_n_47, add_23_2_n_48, add_23_2_n_49, add_23_2_n_50;
  wire add_23_2_n_51, add_23_2_n_52, add_23_2_n_53, add_23_2_n_54,
       add_23_2_n_55, add_23_2_n_57, add_23_2_n_59, add_23_2_n_60;
  wire add_23_2_n_61, add_23_2_n_62, add_23_2_n_63, add_23_2_n_64,
       add_23_2_n_65, add_23_2_n_66, add_23_2_n_67, add_23_2_n_68;
  wire add_23_2_n_69, add_23_2_n_70, add_23_2_n_71, add_23_2_n_72,
       add_23_2_n_73, add_23_2_n_74, add_23_2_n_75, add_23_2_n_76;
  wire add_23_2_n_77, add_23_2_n_78, add_23_2_n_79, add_23_2_n_80,
       add_23_2_n_81, add_23_2_n_83, add_23_2_n_85, add_23_2_n_87;
  wire add_23_2_n_89, add_23_2_n_90, add_23_2_n_91, add_23_2_n_92,
       add_23_2_n_94, add_23_2_n_95, add_23_2_n_96, add_23_2_n_97;
  wire add_23_2_n_98, add_23_2_n_99, add_23_2_n_100, add_23_2_n_101,
       add_23_2_n_102, add_23_2_n_103, add_23_2_n_104, add_23_2_n_105;
  wire add_23_2_n_106, add_23_2_n_109, add_23_2_n_110, add_23_2_n_111,
       add_23_2_n_112, add_23_2_n_113, add_23_2_n_114, add_23_2_n_115;
  wire add_23_2_n_116, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_181, n_183, n_184, n_186, n_187, n_188, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_209, n_210, n_211, n_213;
  wire n_214, n_215, n_216, n_217, n_219, n_220, n_224, n_225;
  wire n_226;
  MXI2XL add_23_2_g751(.A (add_23_2_n_18), .B (in2[17]), .S0
       (add_23_2_n_115), .Y (out1[17]));
  MXI2XL add_23_2_g752(.A (add_23_2_n_29), .B (in2[9]), .S0
       (add_23_2_n_100), .Y (out1[9]));
  MXI2XL add_23_2_g754(.A (add_23_2_n_15), .B (in2[19]), .S0
       (add_23_2_n_101), .Y (out1[19]));
  MXI2XL add_23_2_g755(.A (add_23_2_n_30), .B (in2[21]), .S0
       (add_23_2_n_112), .Y (out1[21]));
  MXI2XL add_23_2_g756(.A (add_23_2_n_17), .B (in2[23]), .S0
       (add_23_2_n_104), .Y (out1[23]));
  MXI2XL add_23_2_g757(.A (n_178), .B (n_177), .S0 (add_23_2_n_105), .Y
       (out1[27]));
  MXI2XL add_23_2_g758(.A (add_23_2_n_32), .B (in2[29]), .S0
       (add_23_2_n_106), .Y (out1[29]));
  MXI2XL add_23_2_g759(.A (add_23_2_n_14), .B (in2[25]), .S0
       (add_23_2_n_111), .Y (out1[25]));
  MXI2XL add_23_2_g760(.A (n_213), .B (n_214), .S0 (add_23_2_n_116), .Y
       (out1[26]));
  MXI2XL add_23_2_g761(.A (add_23_2_n_11), .B (in2[24]), .S0
       (add_23_2_n_5), .Y (out1[24]));
  MXI2XL add_23_2_g762(.A (add_23_2_n_22), .B (in2[22]), .S0
       (add_23_2_n_102), .Y (out1[22]));
  MXI2XL add_23_2_g763(.A (add_23_2_n_25), .B (in2[28]), .S0
       (add_23_2_n_110), .Y (out1[28]));
  MXI2XL add_23_2_g764(.A (add_23_2_n_28), .B (in2[20]), .S0
       (add_23_2_n_114), .Y (out1[20]));
  MXI2XL add_23_2_g765(.A (add_23_2_n_8), .B (in2[18]), .S0
       (add_23_2_n_109), .Y (out1[18]));
  MXI2XL add_23_2_g766(.A (add_23_2_n_34), .B (in2[31]), .S0
       (add_23_2_n_113), .Y (out1[31]));
  MXI2XL add_23_2_g767(.A (add_23_2_n_20), .B (in2[30]), .S0
       (add_23_2_n_103), .Y (out1[30]));
  MXI2XL add_23_2_g768(.A (n_210), .B (n_209), .S0 (add_23_2_n_95), .Y
       (out1[13]));
  MXI2XL add_23_2_g769(.A (add_23_2_n_31), .B (in2[11]), .S0
       (add_23_2_n_94), .Y (out1[11]));
  MXI2XL add_23_2_g770(.A (n_225), .B (n_224), .S0 (add_23_2_n_92), .Y
       (out1[15]));
  MXI2XL add_23_2_g773(.A (add_23_2_n_9), .B (in2[14]), .S0
       (add_23_2_n_97), .Y (out1[14]));
  MXI2XL add_23_2_g774(.A (add_23_2_n_26), .B (in2[12]), .S0
       (add_23_2_n_98), .Y (out1[12]));
  MXI2XL add_23_2_g775(.A (add_23_2_n_27), .B (in2[10]), .S0
       (add_23_2_n_99), .Y (out1[10]));
  NOR2XL add_23_2_g776(.A (add_23_2_n_78), .B (add_23_2_n_96), .Y
       (add_23_2_n_116));
  NOR2XL add_23_2_g777(.A (add_23_2_n_24), .B (add_23_2_n_96), .Y
       (add_23_2_n_115));
  NOR2XL add_23_2_g779(.A (n_204), .B (add_23_2_n_96), .Y
       (add_23_2_n_114));
  NOR2XL add_23_2_g780(.A (add_23_2_n_74), .B (add_23_2_n_96), .Y
       (add_23_2_n_113));
  NOR2XL add_23_2_g781(.A (add_23_2_n_69), .B (add_23_2_n_96), .Y
       (add_23_2_n_112));
  NOR2XL add_23_2_g782(.A (add_23_2_n_80), .B (add_23_2_n_96), .Y
       (add_23_2_n_111));
  NOR2XL add_23_2_g783(.A (add_23_2_n_79), .B (add_23_2_n_96), .Y
       (add_23_2_n_110));
  NOR2XL add_23_2_g784(.A (add_23_2_n_42), .B (add_23_2_n_96), .Y
       (add_23_2_n_109));
  MXI2XL add_23_2_g785(.A (add_23_2_n_23), .B (in2[6]), .S0
       (add_23_2_n_91), .Y (out1[6]));
  MXI2XL add_23_2_g787(.A (add_23_2_n_10), .B (in2[8]), .S0 (n_220), .Y
       (out1[8]));
  NOR2XL add_23_2_g788(.A (add_23_2_n_76), .B (add_23_2_n_96), .Y
       (add_23_2_n_106));
  NOR2XL add_23_2_g789(.A (add_23_2_n_75), .B (add_23_2_n_96), .Y
       (add_23_2_n_105));
  NOR2XL add_23_2_g790(.A (add_23_2_n_64), .B (add_23_2_n_96), .Y
       (add_23_2_n_104));
  NOR2XL add_23_2_g791(.A (add_23_2_n_77), .B (add_23_2_n_96), .Y
       (add_23_2_n_103));
  NOR2XL add_23_2_g792(.A (add_23_2_n_70), .B (add_23_2_n_96), .Y
       (add_23_2_n_102));
  NOR2XL add_23_2_g793(.A (add_23_2_n_61), .B (add_23_2_n_96), .Y
       (add_23_2_n_101));
  NOR2X1 add_23_2_g794(.A (add_23_2_n_10), .B (n_219), .Y
       (add_23_2_n_100));
  NOR2X1 add_23_2_g795(.A (add_23_2_n_50), .B (n_219), .Y
       (add_23_2_n_99));
  NOR2X1 add_23_2_g796(.A (n_192), .B (n_219), .Y (add_23_2_n_98));
  NOR2X1 add_23_2_g797(.A (add_23_2_n_73), .B (n_219), .Y
       (add_23_2_n_97));
  NAND2X8 add_23_2_g799(.A (add_23_2_n_65), .B (add_23_2_n_89), .Y
       (add_23_2_n_96));
  NOR2X1 add_23_2_g800(.A (add_23_2_n_71), .B (n_219), .Y
       (add_23_2_n_95));
  NOR2X1 add_23_2_g801(.A (add_23_2_n_60), .B (n_219), .Y
       (add_23_2_n_94));
  MXI2XL add_23_2_g802(.A (add_23_2_n_12), .B (in2[4]), .S0 (n_183), .Y
       (out1[4]));
  NOR2X1 add_23_2_g803(.A (add_23_2_n_67), .B (n_219), .Y
       (add_23_2_n_92));
  NOR2X1 add_23_2_g804(.A (add_23_2_n_49), .B (n_184), .Y
       (add_23_2_n_91));
  NOR2X1 add_23_2_g805(.A (add_23_2_n_12), .B (n_184), .Y
       (add_23_2_n_90));
  CLKAND2X6 add_23_2_g807(.A (add_23_2_n_53), .B (add_23_2_n_83), .Y
       (add_23_2_n_89));
  NOR2X1 add_23_2_g808(.A (add_23_2_n_62), .B (n_184), .Y
       (add_23_2_n_87));
  MXI2XL add_23_2_g809(.A (add_23_2_n_21), .B (in2[2]), .S0 (n_173), .Y
       (out1[2]));
  NOR2X1 add_23_2_g810(.A (add_23_2_n_21), .B (n_174), .Y
       (add_23_2_n_85));
  NOR2X4 add_23_2_g812(.A (add_23_2_n_35), .B (n_176), .Y
       (add_23_2_n_83));
  OAI21X4 add_23_2_g814(.A0 (add_23_2_n_52), .A1 (add_23_2_n_43), .B0
       (add_23_2_n_44), .Y (add_23_2_n_81));
  NAND2X1 add_23_2_g816(.A (in2[24]), .B (add_23_2_n_68), .Y
       (add_23_2_n_80));
  NAND2BX1 add_23_2_g817(.AN (add_23_2_n_63), .B (add_23_2_n_68), .Y
       (add_23_2_n_79));
  NAND2X1 add_23_2_g818(.A (n_186), .B (add_23_2_n_68), .Y
       (add_23_2_n_78));
  NAND2X1 add_23_2_g819(.A (add_23_2_n_72), .B (add_23_2_n_68), .Y
       (add_23_2_n_77));
  NAND3BX1 add_23_2_g820(.AN (add_23_2_n_63), .B (in2[28]), .C
       (add_23_2_n_68), .Y (add_23_2_n_76));
  NAND3X1 add_23_2_g821(.A (n_187), .B (n_215), .C (add_23_2_n_68), .Y
       (add_23_2_n_75));
  NAND2X1 add_23_2_g822(.A (add_23_2_n_66), .B (add_23_2_n_68), .Y
       (add_23_2_n_74));
  OR2XL add_23_2_g824(.A (n_181), .B (n_191), .Y (add_23_2_n_73));
  NOR2X1 add_23_2_g825(.A (add_23_2_n_51), .B (add_23_2_n_63), .Y
       (add_23_2_n_72));
  NAND2X1 add_23_2_g826(.A (in2[12]), .B (n_193), .Y (add_23_2_n_71));
  OR2XL add_23_2_g827(.A (add_23_2_n_41), .B (n_202), .Y
       (add_23_2_n_70));
  NAND2X1 add_23_2_g828(.A (in2[20]), .B (n_203), .Y (add_23_2_n_69));
  NAND3BXL add_23_2_g830(.AN (n_181), .B (n_196), .C (in2[14]), .Y
       (add_23_2_n_67));
  NOR3X1 add_23_2_g831(.A (add_23_2_n_51), .B (add_23_2_n_20), .C
       (add_23_2_n_63), .Y (add_23_2_n_66));
  NOR2X4 add_23_2_g832(.A (add_23_2_n_55), .B (n_190), .Y
       (add_23_2_n_65));
  NAND3BXL add_23_2_g833(.AN (add_23_2_n_41), .B (n_206), .C (in2[22]),
       .Y (add_23_2_n_64));
  CLKAND2X2 add_23_2_g834(.A (add_23_2_n_54), .B (add_23_2_n_57), .Y
       (add_23_2_n_68));
  OR2XL add_23_2_g835(.A (add_23_2_n_23), .B (add_23_2_n_49), .Y
       (add_23_2_n_62));
  OR2XL add_23_2_g836(.A (add_23_2_n_8), .B (add_23_2_n_42), .Y
       (add_23_2_n_61));
  OR2XL add_23_2_g837(.A (add_23_2_n_27), .B (add_23_2_n_50), .Y
       (add_23_2_n_60));
  NAND2X2 add_23_2_g839(.A (add_23_2_n_36), .B (add_23_2_n_40), .Y
       (add_23_2_n_63));
  NAND2X1 add_23_2_g842(.A (add_23_2_n_45), .B (add_23_2_n_38), .Y
       (add_23_2_n_55));
  NOR2X1 add_23_2_g843(.A (add_23_2_n_47), .B (add_23_2_n_41), .Y
       (add_23_2_n_54));
  NOR2X1 add_23_2_g844(.A (add_23_2_n_46), .B (add_23_2_n_49), .Y
       (add_23_2_n_53));
  NOR2X1 add_23_2_g846(.A (add_23_2_n_48), .B (add_23_2_n_50), .Y
       (add_23_2_n_59));
  NOR2X2 add_23_2_g847(.A (add_23_2_n_37), .B (add_23_2_n_42), .Y
       (add_23_2_n_57));
  NAND2X1 add_23_2_g848(.A (in2[11]), .B (in2[10]), .Y (add_23_2_n_48));
  NAND2X1 add_23_2_g849(.A (in2[23]), .B (in2[22]), .Y (add_23_2_n_47));
  NAND2X1 add_23_2_g850(.A (in2[7]), .B (in2[6]), .Y (add_23_2_n_46));
  NOR2X1 add_23_2_g851(.A (n_226), .B (add_23_2_n_9), .Y
       (add_23_2_n_45));
  NOR2X4 add_23_2_g852(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_52));
  NAND2X1 add_23_2_g853(.A (in2[29]), .B (in2[28]), .Y (add_23_2_n_51));
  NAND2X2 add_23_2_g854(.A (in2[9]), .B (in2[8]), .Y (add_23_2_n_50));
  NAND2X1 add_23_2_g855(.A (in2[5]), .B (in2[4]), .Y (add_23_2_n_49));
  NAND2X1 add_23_2_g858(.A (in2[19]), .B (in2[18]), .Y (add_23_2_n_37));
  NOR2X1 add_23_2_g859(.A (n_179), .B (n_217), .Y (add_23_2_n_36));
  NAND2X1 add_23_2_g860(.A (in2[3]), .B (in2[2]), .Y (add_23_2_n_35));
  NAND2X4 add_23_2_g861(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_44));
  NAND2X8 add_23_2_g862(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_43));
  NAND2X2 add_23_2_g863(.A (in2[17]), .B (in2[16]), .Y (add_23_2_n_42));
  NAND2X1 add_23_2_g864(.A (in2[21]), .B (in2[20]), .Y (add_23_2_n_41));
  NOR2X2 add_23_2_g865(.A (add_23_2_n_14), .B (add_23_2_n_11), .Y
       (add_23_2_n_40));
  NOR2X1 add_23_2_g866(.A (n_211), .B (add_23_2_n_26), .Y
       (add_23_2_n_38));
  INVXL add_23_2_g867(.A (in2[31]), .Y (add_23_2_n_34));
  INVXL add_23_2_g869(.A (in2[29]), .Y (add_23_2_n_32));
  INVXL add_23_2_g870(.A (in2[11]), .Y (add_23_2_n_31));
  INVXL add_23_2_g871(.A (in2[21]), .Y (add_23_2_n_30));
  INVXL add_23_2_g872(.A (in2[9]), .Y (add_23_2_n_29));
  INVXL add_23_2_g873(.A (in2[20]), .Y (add_23_2_n_28));
  INVX1 add_23_2_g874(.A (in2[10]), .Y (add_23_2_n_27));
  INVX1 add_23_2_g875(.A (in2[12]), .Y (add_23_2_n_26));
  INVXL add_23_2_g876(.A (in2[28]), .Y (add_23_2_n_25));
  INVX1 add_23_2_g877(.A (in2[16]), .Y (add_23_2_n_24));
  INVX1 add_23_2_g878(.A (in2[6]), .Y (add_23_2_n_23));
  INVXL add_23_2_g879(.A (in2[22]), .Y (add_23_2_n_22));
  INVX1 add_23_2_g880(.A (in2[2]), .Y (add_23_2_n_21));
  INVX1 add_23_2_g881(.A (in2[30]), .Y (add_23_2_n_20));
  INVXL add_23_2_g885(.A (in2[17]), .Y (add_23_2_n_18));
  INVXL add_23_2_g886(.A (in2[23]), .Y (add_23_2_n_17));
  INVXL add_23_2_g889(.A (in2[19]), .Y (add_23_2_n_15));
  INVX1 add_23_2_g890(.A (in2[25]), .Y (add_23_2_n_14));
  INVX1 add_23_2_g893(.A (in2[4]), .Y (add_23_2_n_12));
  INVX1 add_23_2_g894(.A (in2[24]), .Y (add_23_2_n_11));
  INVX1 add_23_2_g895(.A (in2[8]), .Y (add_23_2_n_10));
  INVX1 add_23_2_g896(.A (in2[14]), .Y (add_23_2_n_9));
  INVX1 add_23_2_g897(.A (in2[18]), .Y (add_23_2_n_8));
  MXI2XL add_23_2_g2(.A (in2[16]), .B (add_23_2_n_24), .S0
       (add_23_2_n_96), .Y (out1[16]));
  XNOR2X1 add_23_2_g898(.A (add_23_2_n_43), .B (add_23_2_n_4), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g899(.AN (add_23_2_n_68), .B (add_23_2_n_96), .Y
       (add_23_2_n_5));
  NOR2BX1 add_23_2_g900(.AN (add_23_2_n_44), .B (add_23_2_n_52), .Y
       (add_23_2_n_4));
  CLKXOR2X1 add_23_2_g901(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  XOR2XL add_23_2_g902(.A (in2[7]), .B (add_23_2_n_87), .Y (out1[7]));
  CLKXOR2X1 add_23_2_g903(.A (in2[3]), .B (add_23_2_n_85), .Y
       (out1[3]));
  XOR2XL add_23_2_g904(.A (in2[5]), .B (add_23_2_n_90), .Y (out1[5]));
  BUFX2 fopt(.A (n_175), .Y (n_173));
  INVXL fopt905(.A (n_175), .Y (n_174));
  INVXL fopt906(.A (n_176), .Y (n_175));
  CLKINVX4 fopt907(.A (add_23_2_n_81), .Y (n_176));
  INVXL fopt908(.A (n_178), .Y (n_177));
  INVXL fopt909(.A (in2[27]), .Y (n_178));
  CLKINVX2 fopt910(.A (in2[27]), .Y (n_179));
  INVXL fopt911(.A (add_23_2_n_38), .Y (n_181));
  INVXL fopt912(.A (n_184), .Y (n_183));
  CLKINVX1 fopt913(.A (add_23_2_n_83), .Y (n_184));
  INVXL fopt914(.A (n_188), .Y (n_186));
  INVXL fopt915(.A (n_188), .Y (n_187));
  INVXL fopt916(.A (add_23_2_n_40), .Y (n_188));
  CLKINVX1 fopt917(.A (add_23_2_n_59), .Y (n_190));
  INVXL fopt918(.A (n_195), .Y (n_191));
  BUFX2 fopt919(.A (n_194), .Y (n_192));
  INVXL fopt920(.A (n_194), .Y (n_193));
  INVXL fopt921(.A (n_195), .Y (n_194));
  INVXL fopt922(.A (n_197), .Y (n_195));
  INVXL fopt923(.A (n_197), .Y (n_196));
  INVXL fopt924(.A (add_23_2_n_59), .Y (n_197));
  INVXL fopt927(.A (n_205), .Y (n_202));
  INVXL fopt928(.A (n_204), .Y (n_203));
  INVXL fopt929(.A (n_205), .Y (n_204));
  INVXL fopt930(.A (n_207), .Y (n_205));
  INVXL fopt931(.A (n_207), .Y (n_206));
  INVXL fopt932(.A (add_23_2_n_57), .Y (n_207));
  INVXL fopt933(.A (n_210), .Y (n_209));
  INVXL fopt934(.A (in2[13]), .Y (n_210));
  CLKINVX2 fopt935(.A (in2[13]), .Y (n_211));
  INVXL fopt936(.A (n_214), .Y (n_213));
  INVXL fopt937(.A (n_216), .Y (n_214));
  INVXL fopt938(.A (n_216), .Y (n_215));
  INVXL fopt939(.A (in2[26]), .Y (n_216));
  CLKINVX2 fopt940(.A (in2[26]), .Y (n_217));
  INVXL fopt941(.A (n_219), .Y (n_220));
  CLKINVX2 fopt942(.A (add_23_2_n_89), .Y (n_219));
  INVXL fopt943(.A (n_225), .Y (n_224));
  INVXL fopt944(.A (in2[15]), .Y (n_225));
  CLKINVX2 fopt945(.A (in2[15]), .Y (n_226));
endmodule


