`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 30 2023 21:44:29 CST (May 30 2023 13:44:29 UTC)

module SobelFilter_GreaterThan_6Sx2S_1U_4(in2, in1, out1);
  input [5:0] in2;
  input [1:0] in1;
  output out1;
  wire [5:0] in2;
  wire [1:0] in1;
  wire out1;
  wire gt_21_56_n_0, gt_21_56_n_1, gt_21_56_n_2, gt_21_56_n_3,
       gt_21_56_n_4, gt_21_56_n_5, gt_21_56_n_6, gt_21_56_n_7;
  wire gt_21_56_n_8, gt_21_56_n_9, gt_21_56_n_10, gt_21_56_n_11,
       gt_21_56_n_12, gt_21_56_n_13, gt_21_56_n_14, gt_21_56_n_15;
  wire gt_21_56_n_16, gt_21_56_n_17;
  AOI21X1 gt_21_56_g176(.A0 (gt_21_56_n_5), .A1 (gt_21_56_n_17), .B0
       (gt_21_56_n_8), .Y (out1));
  OAI21X1 gt_21_56_g177(.A0 (gt_21_56_n_8), .A1 (gt_21_56_n_16), .B0
       (gt_21_56_n_11), .Y (gt_21_56_n_17));
  AOI31X1 gt_21_56_g178(.A0 (gt_21_56_n_15), .A1 (gt_21_56_n_7), .A2
       (gt_21_56_n_4), .B0 (gt_21_56_n_14), .Y (gt_21_56_n_16));
  OAI211X1 gt_21_56_g179(.A0 (gt_21_56_n_1), .A1 (in2[3]), .B0
       (gt_21_56_n_13), .C0 (gt_21_56_n_10), .Y (gt_21_56_n_15));
  OAI2BB1X1 gt_21_56_g180(.A0N (gt_21_56_n_7), .A1N (gt_21_56_n_12),
       .B0 (gt_21_56_n_11), .Y (gt_21_56_n_14));
  OAI211X1 gt_21_56_g181(.A0 (gt_21_56_n_2), .A1 (gt_21_56_n_9), .B0
       (gt_21_56_n_3), .C0 (gt_21_56_n_6), .Y (gt_21_56_n_13));
  OAI31X1 gt_21_56_g182(.A0 (gt_21_56_n_8), .A1 (gt_21_56_n_1), .A2
       (in2[4]), .B0 (gt_21_56_n_5), .Y (gt_21_56_n_12));
  OA21X1 gt_21_56_g183(.A0 (gt_21_56_n_8), .A1 (gt_21_56_n_5), .B0
       (gt_21_56_n_5), .Y (gt_21_56_n_11));
  NAND3BXL gt_21_56_g184(.AN (in2[2]), .B (gt_21_56_n_3), .C (in1[1]),
       .Y (gt_21_56_n_10));
  AOI22X1 gt_21_56_g185(.A0 (in2[0]), .A1 (gt_21_56_n_0), .B0 (in2[1]),
       .B1 (gt_21_56_n_1), .Y (gt_21_56_n_9));
  INVX1 gt_21_56_g186(.A (gt_21_56_n_8), .Y (gt_21_56_n_7));
  NOR2BX1 gt_21_56_g187(.AN (in2[5]), .B (in1[1]), .Y (gt_21_56_n_8));
  NAND2X1 gt_21_56_g188(.A (in2[2]), .B (gt_21_56_n_1), .Y
       (gt_21_56_n_6));
  NAND2BX1 gt_21_56_g189(.AN (in2[5]), .B (in1[1]), .Y (gt_21_56_n_5));
  NAND2X1 gt_21_56_g190(.A (in2[4]), .B (gt_21_56_n_1), .Y
       (gt_21_56_n_4));
  NAND2X1 gt_21_56_g191(.A (in2[3]), .B (gt_21_56_n_1), .Y
       (gt_21_56_n_3));
  NOR2X1 gt_21_56_g192(.A (gt_21_56_n_1), .B (in2[1]), .Y
       (gt_21_56_n_2));
  INVX1 gt_21_56_g193(.A (in1[1]), .Y (gt_21_56_n_1));
  INVX1 gt_21_56_g194(.A (in1[0]), .Y (gt_21_56_n_0));
endmodule


