`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 06:00:55 CST (May 14 2023 22:00:55 UTC)

module SobelFilter_Add_33Sx8U_33S_1(in2, in1, out1);
  input [32:0] in2;
  input [7:0] in1;
  output [32:0] out1;
  wire [32:0] in2;
  wire [7:0] in1;
  wire [32:0] out1;
  wire add_23_2_n_5, add_23_2_n_6, add_23_2_n_7, add_23_2_n_14,
       add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19;
  wire add_23_2_n_20, add_23_2_n_21, add_23_2_n_22, add_23_2_n_23,
       add_23_2_n_24, add_23_2_n_25, add_23_2_n_26, add_23_2_n_27;
  wire add_23_2_n_28, add_23_2_n_29, add_23_2_n_30, add_23_2_n_31,
       add_23_2_n_32, add_23_2_n_33, add_23_2_n_34, add_23_2_n_35;
  wire add_23_2_n_36, add_23_2_n_37, add_23_2_n_38, add_23_2_n_39,
       add_23_2_n_40, add_23_2_n_41, add_23_2_n_42, add_23_2_n_43;
  wire add_23_2_n_44, add_23_2_n_45, add_23_2_n_46, add_23_2_n_47,
       add_23_2_n_48, add_23_2_n_49, add_23_2_n_50, add_23_2_n_51;
  wire add_23_2_n_52, add_23_2_n_53, add_23_2_n_54, add_23_2_n_55,
       add_23_2_n_56, add_23_2_n_57, add_23_2_n_58, add_23_2_n_59;
  wire add_23_2_n_60, add_23_2_n_61, add_23_2_n_62, add_23_2_n_63,
       add_23_2_n_64, add_23_2_n_65, add_23_2_n_66, add_23_2_n_67;
  wire add_23_2_n_68, add_23_2_n_69, add_23_2_n_70, add_23_2_n_71,
       add_23_2_n_72, add_23_2_n_74, add_23_2_n_75, add_23_2_n_76;
  wire add_23_2_n_77, add_23_2_n_78, add_23_2_n_79, add_23_2_n_80,
       add_23_2_n_81, add_23_2_n_82, add_23_2_n_83, add_23_2_n_84;
  wire add_23_2_n_85, add_23_2_n_86, add_23_2_n_87, add_23_2_n_88,
       add_23_2_n_89, add_23_2_n_90, add_23_2_n_91, add_23_2_n_92;
  wire add_23_2_n_93, add_23_2_n_94, add_23_2_n_95, add_23_2_n_96,
       add_23_2_n_97, add_23_2_n_98, add_23_2_n_99, add_23_2_n_100;
  wire add_23_2_n_101, add_23_2_n_102, add_23_2_n_103, add_23_2_n_104,
       add_23_2_n_105, add_23_2_n_106, add_23_2_n_107, add_23_2_n_108;
  wire add_23_2_n_109, add_23_2_n_110, add_23_2_n_111, add_23_2_n_112,
       add_23_2_n_113, add_23_2_n_114, add_23_2_n_115, add_23_2_n_116;
  wire add_23_2_n_117, add_23_2_n_118, add_23_2_n_119, add_23_2_n_120,
       add_23_2_n_121, add_23_2_n_122, add_23_2_n_123, add_23_2_n_124;
  wire add_23_2_n_125, add_23_2_n_126, add_23_2_n_127, add_23_2_n_128,
       add_23_2_n_129, add_23_2_n_131, add_23_2_n_132, add_23_2_n_133;
  wire add_23_2_n_134, add_23_2_n_135, add_23_2_n_136, add_23_2_n_137,
       add_23_2_n_138, add_23_2_n_139, add_23_2_n_140, add_23_2_n_142;
  wire add_23_2_n_143, add_23_2_n_144, add_23_2_n_145, add_23_2_n_146,
       add_23_2_n_147, add_23_2_n_148, add_23_2_n_149, add_23_2_n_150;
  wire add_23_2_n_151, n_217, n_219, n_220, n_221, n_223, n_224, n_225;
  wire n_227, n_228, n_229, n_230, n_231, n_232, n_234, n_236;
  wire n_237, n_238, n_239, n_240, n_241, n_243, n_246, n_247;
  wire n_248, n_250, n_251, n_252, n_253, n_255, n_256, n_257;
  wire n_259, n_261, n_268;
  MXI2XL add_23_2_g789(.A (add_23_2_n_24), .B (in2[17]), .S0
       (add_23_2_n_150), .Y (out1[17]));
  MXI2XL add_23_2_g791(.A (add_23_2_n_20), .B (in2[24]), .S0
       (add_23_2_n_149), .Y (out1[24]));
  MXI2XL add_23_2_g792(.A (add_23_2_n_23), .B (in2[19]), .S0
       (add_23_2_n_137), .Y (out1[19]));
  MXI2XL add_23_2_g793(.A (add_23_2_n_37), .B (in2[29]), .S0
       (add_23_2_n_140), .Y (out1[29]));
  MXI2XL add_23_2_g794(.A (add_23_2_n_34), .B (in2[25]), .S0
       (add_23_2_n_145), .Y (out1[25]));
  MXI2XL add_23_2_g795(.A (add_23_2_n_35), .B (in2[23]), .S0
       (add_23_2_n_135), .Y (out1[23]));
  MXI2XL add_23_2_g796(.A (add_23_2_n_36), .B (in2[27]), .S0
       (add_23_2_n_136), .Y (out1[27]));
  MXI2XL add_23_2_g797(.A (add_23_2_n_25), .B (in2[21]), .S0
       (add_23_2_n_144), .Y (out1[21]));
  MXI2XL add_23_2_g798(.A (add_23_2_n_30), .B (in2[18]), .S0
       (add_23_2_n_151), .Y (out1[18]));
  MXI2XL add_23_2_g799(.A (add_23_2_n_17), .B (in2[26]), .S0
       (add_23_2_n_143), .Y (out1[26]));
  MXI2XL add_23_2_g800(.A (add_23_2_n_32), .B (in2[22]), .S0
       (add_23_2_n_142), .Y (out1[22]));
  MXI2XL add_23_2_g801(.A (add_23_2_n_31), .B (in2[28]), .S0
       (add_23_2_n_139), .Y (out1[28]));
  MXI2XL add_23_2_g802(.A (add_23_2_n_33), .B (in2[20]), .S0
       (add_23_2_n_148), .Y (out1[20]));
  MXI2XL add_23_2_g803(.A (add_23_2_n_38), .B (in2[31]), .S0
       (add_23_2_n_146), .Y (out1[31]));
  MXI2XL add_23_2_g804(.A (add_23_2_n_27), .B (in2[32]), .S0
       (add_23_2_n_147), .Y (out1[32]));
  MXI2XL add_23_2_g805(.A (add_23_2_n_29), .B (in2[30]), .S0
       (add_23_2_n_138), .Y (out1[30]));
  MXI2XL add_23_2_g808(.A (add_23_2_n_22), .B (in2[15]), .S0
       (add_23_2_n_126), .Y (out1[15]));
  MXI2XL add_23_2_g809(.A (add_23_2_n_18), .B (in2[16]), .S0 (n_268),
       .Y (out1[16]));
  MXI2XL add_23_2_g810(.A (add_23_2_n_19), .B (in2[14]), .S0
       (add_23_2_n_131), .Y (out1[14]));
  MXI2XL add_23_2_g812(.A (add_23_2_n_16), .B (in2[10]), .S0
       (add_23_2_n_133), .Y (out1[10]));
  NOR2XL add_23_2_g813(.A (add_23_2_n_59), .B (n_261), .Y
       (add_23_2_n_151));
  NOR2XL add_23_2_g814(.A (add_23_2_n_18), .B (n_261), .Y
       (add_23_2_n_150));
  NOR2XL add_23_2_g815(.A (add_23_2_n_95), .B (n_261), .Y
       (add_23_2_n_149));
  NOR2XL add_23_2_g816(.A (n_229), .B (n_261), .Y (add_23_2_n_148));
  NOR2XL add_23_2_g817(.A (add_23_2_n_107), .B (n_261), .Y
       (add_23_2_n_147));
  NOR2XL add_23_2_g818(.A (add_23_2_n_104), .B (n_261), .Y
       (add_23_2_n_146));
  NOR2XL add_23_2_g819(.A (add_23_2_n_111), .B (n_261), .Y
       (add_23_2_n_145));
  NOR2XL add_23_2_g820(.A (add_23_2_n_101), .B (n_261), .Y
       (add_23_2_n_144));
  NOR2XL add_23_2_g821(.A (add_23_2_n_112), .B (n_261), .Y
       (add_23_2_n_143));
  NOR2XL add_23_2_g822(.A (add_23_2_n_97), .B (n_261), .Y
       (add_23_2_n_142));
  MXI2XL add_23_2_g825(.A (in2[8]), .B (add_23_2_n_21), .S0 (n_217), .Y
       (out1[8]));
  NOR2XL add_23_2_g827(.A (add_23_2_n_106), .B (n_261), .Y
       (add_23_2_n_140));
  NOR2XL add_23_2_g828(.A (add_23_2_n_110), .B (n_261), .Y
       (add_23_2_n_139));
  NOR2XL add_23_2_g829(.A (add_23_2_n_108), .B (n_261), .Y
       (add_23_2_n_138));
  NOR2XL add_23_2_g830(.A (add_23_2_n_81), .B (n_261), .Y
       (add_23_2_n_137));
  NOR2XL add_23_2_g831(.A (add_23_2_n_105), .B (n_261), .Y
       (add_23_2_n_136));
  NOR2XL add_23_2_g832(.A (add_23_2_n_90), .B (n_261), .Y
       (add_23_2_n_135));
  NOR2X1 add_23_2_g833(.A (add_23_2_n_71), .B (n_219), .Y
       (add_23_2_n_134));
  NOR2X1 add_23_2_g834(.A (add_23_2_n_45), .B (n_217), .Y
       (add_23_2_n_133));
  NOR2X1 add_23_2_g835(.A (add_23_2_n_21), .B (n_219), .Y
       (add_23_2_n_132));
  NOR2BX1 add_23_2_g836(.AN (add_23_2_n_100), .B (n_217), .Y
       (add_23_2_n_131));
  NOR2X4 add_23_2_g838(.A (add_23_2_n_91), .B (add_23_2_n_125), .Y
       (add_23_2_n_129));
  NOR2X1 add_23_2_g839(.A (add_23_2_n_99), .B (n_220), .Y
       (add_23_2_n_128));
  NOR2X1 add_23_2_g840(.A (add_23_2_n_68), .B (n_220), .Y
       (add_23_2_n_127));
  NOR2X1 add_23_2_g841(.A (add_23_2_n_89), .B (n_217), .Y
       (add_23_2_n_126));
  NOR2X4 add_23_2_g842(.A (add_23_2_n_114), .B (add_23_2_n_120), .Y
       (add_23_2_n_125));
  NOR2BX1 add_23_2_g844(.AN (n_223), .B (add_23_2_n_121), .Y
       (add_23_2_n_124));
  NOR2X1 add_23_2_g847(.A (add_23_2_n_115), .B (add_23_2_n_119), .Y
       (add_23_2_n_123));
  NOR2X1 add_23_2_g848(.A (add_23_2_n_76), .B (n_243), .Y
       (add_23_2_n_122));
  NOR2X1 add_23_2_g849(.A (add_23_2_n_49), .B (n_243), .Y
       (add_23_2_n_121));
  NOR2X4 add_23_2_g850(.A (add_23_2_n_102), .B (add_23_2_n_117), .Y
       (add_23_2_n_120));
  NOR2X1 add_23_2_g851(.A (add_23_2_n_98), .B (n_243), .Y
       (add_23_2_n_119));
  NOR2BX1 add_23_2_g852(.AN (n_256), .B (add_23_2_n_6), .Y
       (add_23_2_n_118));
  NOR2X2 add_23_2_g854(.A (add_23_2_n_93), .B (add_23_2_n_116), .Y
       (add_23_2_n_117));
  NOR2X2 add_23_2_g856(.A (add_23_2_n_80), .B (add_23_2_n_113), .Y
       (add_23_2_n_116));
  OAI21X1 add_23_2_g857(.A0 (n_251), .A1 (add_23_2_n_103), .B0
       (add_23_2_n_62), .Y (add_23_2_n_115));
  OAI21X2 add_23_2_g858(.A0 (add_23_2_n_84), .A1 (add_23_2_n_103), .B0
       (add_23_2_n_94), .Y (add_23_2_n_114));
  NOR2X2 add_23_2_g859(.A (add_23_2_n_51), .B (add_23_2_n_109), .Y
       (add_23_2_n_113));
  OR2XL add_23_2_g861(.A (add_23_2_n_48), .B (add_23_2_n_95), .Y
       (add_23_2_n_112));
  NAND2X1 add_23_2_g862(.A (in2[24]), .B (add_23_2_n_96), .Y
       (add_23_2_n_111));
  NAND2XL add_23_2_g863(.A (n_236), .B (add_23_2_n_96), .Y
       (add_23_2_n_110));
  NOR2X4 add_23_2_g864(.A (add_23_2_n_66), .B (add_23_2_n_42), .Y
       (add_23_2_n_109));
  NAND3BXL add_23_2_g865(.AN (add_23_2_n_63), .B (add_23_2_n_96), .C
       (n_239), .Y (add_23_2_n_108));
  NAND2BXL add_23_2_g866(.AN (add_23_2_n_92), .B (add_23_2_n_96), .Y
       (add_23_2_n_107));
  NAND3X1 add_23_2_g867(.A (add_23_2_n_96), .B (in2[28]), .C (n_237),
       .Y (add_23_2_n_106));
  NAND3BXL add_23_2_g868(.AN (add_23_2_n_48), .B (add_23_2_n_96), .C
       (in2[26]), .Y (add_23_2_n_105));
  NAND2XL add_23_2_g869(.A (add_23_2_n_7), .B (add_23_2_n_96), .Y
       (add_23_2_n_104));
  NAND2X2 add_23_2_g872(.A (add_23_2_n_83), .B (add_23_2_n_75), .Y
       (add_23_2_n_102));
  NAND2X1 add_23_2_g873(.A (in2[20]), .B (n_228), .Y (add_23_2_n_101));
  NOR2X1 add_23_2_g874(.A (add_23_2_n_47), .B (add_23_2_n_71), .Y
       (add_23_2_n_100));
  NAND2X1 add_23_2_g875(.A (in2[12]), .B (add_23_2_n_72), .Y
       (add_23_2_n_99));
  OR2XL add_23_2_g876(.A (n_253), .B (add_23_2_n_76), .Y
       (add_23_2_n_98));
  OR2XL add_23_2_g877(.A (add_23_2_n_44), .B (n_227), .Y
       (add_23_2_n_97));
  NOR2X2 add_23_2_g878(.A (add_23_2_n_5), .B (add_23_2_n_82), .Y
       (add_23_2_n_103));
  INVX1 add_23_2_g879(.A (add_23_2_n_96), .Y (add_23_2_n_95));
  AOI2BB1X1 add_23_2_g880(.A0N (add_23_2_n_62), .A1N (add_23_2_n_46),
       .B0 (add_23_2_n_53), .Y (add_23_2_n_94));
  OAI21X1 add_23_2_g881(.A0 (add_23_2_n_60), .A1 (add_23_2_n_50), .B0
       (add_23_2_n_52), .Y (add_23_2_n_93));
  NAND4BX1 add_23_2_g883(.AN (add_23_2_n_63), .B (add_23_2_n_70), .C
       (in2[31]), .D (in2[30]), .Y (add_23_2_n_92));
  NAND2X2 add_23_2_g884(.A (add_23_2_n_72), .B (add_23_2_n_67), .Y
       (add_23_2_n_91));
  NAND3BXL add_23_2_g885(.AN (add_23_2_n_44), .B (n_231), .C (in2[22]),
       .Y (add_23_2_n_90));
  NAND3BXL add_23_2_g886(.AN (add_23_2_n_47), .B (add_23_2_n_72), .C
       (in2[14]), .Y (add_23_2_n_89));
  NOR2X2 add_23_2_g887(.A (add_23_2_n_69), .B (add_23_2_n_74), .Y
       (add_23_2_n_96));
  INVX1 add_23_2_g892(.A (add_23_2_n_83), .Y (add_23_2_n_84));
  NOR2X1 add_23_2_g893(.A (add_23_2_n_65), .B (add_23_2_n_43), .Y
       (add_23_2_n_82));
  OR2XL add_23_2_g894(.A (add_23_2_n_30), .B (add_23_2_n_59), .Y
       (add_23_2_n_81));
  NAND2X2 add_23_2_g895(.A (add_23_2_n_61), .B (add_23_2_n_64), .Y
       (add_23_2_n_80));
  NOR2X1 add_23_2_g896(.A (add_23_2_n_5), .B (n_259), .Y
       (add_23_2_n_88));
  NAND2BX1 add_23_2_g897(.AN (n_250), .B (add_23_2_n_62), .Y
       (add_23_2_n_87));
  NAND2X1 add_23_2_g898(.A (n_255), .B (add_23_2_n_64), .Y
       (add_23_2_n_86));
  NAND2BX1 add_23_2_g899(.AN (add_23_2_n_49), .B (n_224), .Y
       (add_23_2_n_85));
  NOR2X1 add_23_2_g900(.A (add_23_2_n_51), .B (add_23_2_n_66), .Y
       (add_23_2_n_79));
  NOR2X1 add_23_2_g901(.A (add_23_2_n_57), .B (add_23_2_n_46), .Y
       (add_23_2_n_83));
  INVX1 add_23_2_g904(.A (add_23_2_n_75), .Y (add_23_2_n_76));
  INVX1 add_23_2_g906(.A (add_23_2_n_72), .Y (add_23_2_n_71));
  OR2XL add_23_2_g908(.A (add_23_2_n_41), .B (add_23_2_n_44), .Y
       (add_23_2_n_69));
  OR2XL add_23_2_g910(.A (add_23_2_n_16), .B (add_23_2_n_45), .Y
       (add_23_2_n_68));
  NOR3X2 add_23_2_g911(.A (add_23_2_n_19), .B (add_23_2_n_22), .C
       (add_23_2_n_47), .Y (add_23_2_n_67));
  NOR2X1 add_23_2_g912(.A (add_23_2_n_53), .B (n_234), .Y
       (add_23_2_n_78));
  NAND2X1 add_23_2_g913(.A (add_23_2_n_52), .B (add_23_2_n_61), .Y
       (add_23_2_n_77));
  NOR2X1 add_23_2_g914(.A (add_23_2_n_43), .B (add_23_2_n_49), .Y
       (add_23_2_n_75));
  NAND2X2 add_23_2_g915(.A (add_23_2_n_54), .B (add_23_2_n_58), .Y
       (add_23_2_n_74));
  NOR2X1 add_23_2_g916(.A (add_23_2_n_56), .B (add_23_2_n_45), .Y
       (add_23_2_n_72));
  NOR2X2 add_23_2_g917(.A (add_23_2_n_48), .B (add_23_2_n_55), .Y
       (add_23_2_n_70));
  CLKINVX3 add_23_2_g919(.A (add_23_2_n_60), .Y (add_23_2_n_61));
  INVX1 add_23_2_g920(.A (add_23_2_n_58), .Y (add_23_2_n_59));
  NAND2X1 add_23_2_g921(.A (in2[11]), .B (in2[10]), .Y (add_23_2_n_56));
  NAND2X1 add_23_2_g922(.A (in2[27]), .B (in2[26]), .Y (add_23_2_n_55));
  NOR2X1 add_23_2_g923(.A (add_23_2_n_23), .B (add_23_2_n_30), .Y
       (add_23_2_n_54));
  NOR2X6 add_23_2_g925(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_66));
  NAND2X2 add_23_2_g926(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_65));
  NAND2X2 add_23_2_g927(.A (add_23_2_n_28), .B (add_23_2_n_40), .Y
       (add_23_2_n_64));
  NAND2X1 add_23_2_g928(.A (in2[29]), .B (in2[28]), .Y (add_23_2_n_63));
  NAND2X1 add_23_2_g929(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_62));
  NOR2X8 add_23_2_g930(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_60));
  NOR2X2 add_23_2_g931(.A (add_23_2_n_24), .B (add_23_2_n_18), .Y
       (add_23_2_n_58));
  NOR2X2 add_23_2_g932(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_57));
  NAND2X1 add_23_2_g933(.A (in2[23]), .B (in2[22]), .Y (add_23_2_n_41));
  AND2X1 add_23_2_g934(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_53));
  NAND2X1 add_23_2_g935(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_52));
  NOR2X2 add_23_2_g936(.A (add_23_2_n_26), .B (add_23_2_n_39), .Y
       (add_23_2_n_51));
  NAND2X1 add_23_2_g937(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_50));
  NOR2X2 add_23_2_g938(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_49));
  NAND2X2 add_23_2_g939(.A (in2[25]), .B (in2[24]), .Y (add_23_2_n_48));
  NAND2X1 add_23_2_g940(.A (in2[13]), .B (in2[12]), .Y (add_23_2_n_47));
  NOR2X2 add_23_2_g941(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_46));
  NAND2X1 add_23_2_g942(.A (in2[9]), .B (in2[8]), .Y (add_23_2_n_45));
  NAND2X1 add_23_2_g943(.A (in2[21]), .B (in2[20]), .Y (add_23_2_n_44));
  NOR2X2 add_23_2_g944(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_43));
  NAND2X8 add_23_2_g945(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_42));
  CLKINVX2 add_23_2_g946(.A (in1[2]), .Y (add_23_2_n_40));
  CLKINVX2 add_23_2_g947(.A (in1[1]), .Y (add_23_2_n_39));
  INVXL add_23_2_g950(.A (in2[31]), .Y (add_23_2_n_38));
  INVXL add_23_2_g951(.A (in2[29]), .Y (add_23_2_n_37));
  INVXL add_23_2_g953(.A (in2[27]), .Y (add_23_2_n_36));
  INVXL add_23_2_g954(.A (in2[23]), .Y (add_23_2_n_35));
  INVXL add_23_2_g955(.A (in2[25]), .Y (add_23_2_n_34));
  INVXL add_23_2_g956(.A (in2[20]), .Y (add_23_2_n_33));
  INVXL add_23_2_g957(.A (in2[22]), .Y (add_23_2_n_32));
  INVXL add_23_2_g958(.A (in2[28]), .Y (add_23_2_n_31));
  INVX1 add_23_2_g959(.A (in2[18]), .Y (add_23_2_n_30));
  INVX1 add_23_2_g960(.A (in2[30]), .Y (add_23_2_n_29));
  CLKINVX2 add_23_2_g961(.A (in2[2]), .Y (add_23_2_n_28));
  INVXL add_23_2_g962(.A (in2[32]), .Y (add_23_2_n_27));
  CLKINVX3 add_23_2_g964(.A (in2[1]), .Y (add_23_2_n_26));
  INVXL add_23_2_g965(.A (in2[21]), .Y (add_23_2_n_25));
  INVX1 add_23_2_g966(.A (in2[17]), .Y (add_23_2_n_24));
  INVX1 add_23_2_g967(.A (in2[19]), .Y (add_23_2_n_23));
  INVX1 add_23_2_g970(.A (in2[15]), .Y (add_23_2_n_22));
  INVX1 add_23_2_g971(.A (in2[8]), .Y (add_23_2_n_21));
  INVXL add_23_2_g972(.A (in2[24]), .Y (add_23_2_n_20));
  INVX1 add_23_2_g974(.A (in2[14]), .Y (add_23_2_n_19));
  INVX1 add_23_2_g975(.A (in2[16]), .Y (add_23_2_n_18));
  INVXL add_23_2_g976(.A (in2[26]), .Y (add_23_2_n_17));
  INVX1 add_23_2_g977(.A (in2[10]), .Y (add_23_2_n_16));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_42), .B (add_23_2_n_79), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g978(.AN (add_23_2_n_103), .B (add_23_2_n_122), .Y
       (add_23_2_n_14));
  XNOR2X1 add_23_2_g979(.A (add_23_2_n_88), .B (add_23_2_n_124), .Y
       (out1[5]));
  XOR2XL add_23_2_g980(.A (add_23_2_n_87), .B (add_23_2_n_14), .Y
       (out1[6]));
  CLKXOR2X1 add_23_2_g981(.A (add_23_2_n_86), .B (n_246), .Y (out1[2]));
  CLKXOR2X1 add_23_2_g982(.A (add_23_2_n_85), .B (n_243), .Y (out1[4]));
  XNOR2X1 add_23_2_g983(.A (add_23_2_n_78), .B (add_23_2_n_123), .Y
       (out1[7]));
  CLKXOR2X1 add_23_2_g984(.A (add_23_2_n_77), .B (add_23_2_n_118), .Y
       (out1[3]));
  NOR3BX1 add_23_2_g985(.AN (n_240), .B (add_23_2_n_29), .C
       (add_23_2_n_63), .Y (add_23_2_n_7));
  NOR2BX1 add_23_2_g986(.AN (add_23_2_n_64), .B (n_247), .Y
       (add_23_2_n_6));
  AND2X1 add_23_2_g987(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_5));
  CLKXOR2X1 add_23_2_g988(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  XOR2XL add_23_2_g989(.A (in2[9]), .B (add_23_2_n_132), .Y (out1[9]));
  XOR2XL add_23_2_g990(.A (in2[13]), .B (add_23_2_n_128), .Y
       (out1[13]));
  XOR2XL add_23_2_g991(.A (in2[11]), .B (add_23_2_n_127), .Y
       (out1[11]));
  XOR2XL add_23_2_g992(.A (in2[12]), .B (add_23_2_n_134), .Y
       (out1[12]));
  CLKINVX1 fopt994(.A (n_221), .Y (n_217));
  CLKINVX1 fopt995(.A (n_221), .Y (n_219));
  CLKINVX1 fopt996(.A (n_221), .Y (n_220));
  CLKINVX2 fopt997(.A (add_23_2_n_125), .Y (n_221));
  INVXL fopt998(.A (n_225), .Y (n_223));
  INVXL fopt999(.A (n_225), .Y (n_224));
  INVXL fopt1000(.A (add_23_2_n_65), .Y (n_225));
  INVXL fopt1001(.A (n_230), .Y (n_227));
  INVXL fopt1002(.A (n_229), .Y (n_228));
  INVXL fopt1003(.A (n_230), .Y (n_229));
  INVXL fopt1004(.A (n_232), .Y (n_230));
  INVXL fopt1005(.A (n_232), .Y (n_231));
  BUFX2 fopt1006(.A (add_23_2_n_74), .Y (n_232));
  BUFX2 fopt1007(.A (add_23_2_n_46), .Y (n_234));
  INVXL fopt1008(.A (n_238), .Y (n_236));
  INVXL fopt1009(.A (n_238), .Y (n_237));
  INVXL fopt1010(.A (n_239), .Y (n_238));
  INVXL fopt1011(.A (n_241), .Y (n_239));
  INVXL fopt1012(.A (n_241), .Y (n_240));
  INVXL fopt1013(.A (add_23_2_n_70), .Y (n_241));
  BUFX3 fopt1014(.A (add_23_2_n_117), .Y (n_243));
  INVXL fopt(.A (n_248), .Y (n_246));
  INVXL fopt1015(.A (n_248), .Y (n_247));
  INVXL fopt1016(.A (add_23_2_n_113), .Y (n_248));
  INVXL fopt1017(.A (n_252), .Y (n_250));
  INVXL fopt1018(.A (n_252), .Y (n_251));
  INVXL fopt1019(.A (n_253), .Y (n_252));
  BUFX2 fopt1020(.A (add_23_2_n_57), .Y (n_253));
  INVXL fopt1021(.A (n_257), .Y (n_255));
  INVXL fopt1022(.A (n_257), .Y (n_256));
  INVXL fopt1023(.A (add_23_2_n_50), .Y (n_257));
  BUFX2 fopt1024(.A (add_23_2_n_43), .Y (n_259));
  INVXL fopt1025(.A (n_261), .Y (n_268));
  CLKINVX6 fopt1026(.A (add_23_2_n_129), .Y (n_261));
endmodule


