`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 15 2023 05:59:59 CST (May 14 2023 21:59:59 UTC)

module SobelFilter_Add_32Sx1U_32S_4(in2, in1, out1);
  input [31:0] in2;
  input in1;
  output [31:0] out1;
  wire [31:0] in2;
  wire in1;
  wire [31:0] out1;
  wire inc_add_23_2_1_n_0, inc_add_23_2_1_n_1, inc_add_23_2_1_n_2,
       inc_add_23_2_1_n_3, inc_add_23_2_1_n_4, inc_add_23_2_1_n_5,
       inc_add_23_2_1_n_6, inc_add_23_2_1_n_7;
  wire inc_add_23_2_1_n_8, inc_add_23_2_1_n_9, inc_add_23_2_1_n_10,
       inc_add_23_2_1_n_11, inc_add_23_2_1_n_13, inc_add_23_2_1_n_14,
       inc_add_23_2_1_n_15, inc_add_23_2_1_n_17;
  wire inc_add_23_2_1_n_18, inc_add_23_2_1_n_20, inc_add_23_2_1_n_21,
       inc_add_23_2_1_n_23, inc_add_23_2_1_n_24, inc_add_23_2_1_n_25,
       inc_add_23_2_1_n_26, inc_add_23_2_1_n_29;
  wire inc_add_23_2_1_n_30, inc_add_23_2_1_n_31, inc_add_23_2_1_n_32,
       inc_add_23_2_1_n_33, inc_add_23_2_1_n_34, inc_add_23_2_1_n_35,
       inc_add_23_2_1_n_40, inc_add_23_2_1_n_41;
  wire inc_add_23_2_1_n_42, inc_add_23_2_1_n_43, inc_add_23_2_1_n_44,
       inc_add_23_2_1_n_45, inc_add_23_2_1_n_51, inc_add_23_2_1_n_52,
       inc_add_23_2_1_n_53, inc_add_23_2_1_n_54;
  wire inc_add_23_2_1_n_60;
  XNOR2X1 inc_add_23_2_1_g296(.A (in2[31]), .B (inc_add_23_2_1_n_60),
       .Y (out1[31]));
  XNOR2X1 inc_add_23_2_1_g297(.A (in2[23]), .B (inc_add_23_2_1_n_52),
       .Y (out1[23]));
  XNOR2X1 inc_add_23_2_1_g298(.A (in2[27]), .B (inc_add_23_2_1_n_53),
       .Y (out1[27]));
  XNOR2X1 inc_add_23_2_1_g299(.A (in2[29]), .B (inc_add_23_2_1_n_51),
       .Y (out1[29]));
  XNOR2X1 inc_add_23_2_1_g300(.A (in2[15]), .B (inc_add_23_2_1_n_43),
       .Y (out1[15]));
  XNOR2X1 inc_add_23_2_1_g301(.A (in2[21]), .B (inc_add_23_2_1_n_41),
       .Y (out1[21]));
  XNOR2X1 inc_add_23_2_1_g302(.A (in2[19]), .B (inc_add_23_2_1_n_42),
       .Y (out1[19]));
  XNOR2X1 inc_add_23_2_1_g303(.A (in2[25]), .B (inc_add_23_2_1_n_35),
       .Y (out1[25]));
  XNOR2X1 inc_add_23_2_1_g304(.A (in2[30]), .B (inc_add_23_2_1_n_54),
       .Y (out1[30]));
  XNOR2X1 inc_add_23_2_1_g305(.A (in2[17]), .B (inc_add_23_2_1_n_2), .Y
       (out1[17]));
  XNOR2X1 inc_add_23_2_1_g306(.A (in2[13]), .B (inc_add_23_2_1_n_31),
       .Y (out1[13]));
  XNOR2X1 inc_add_23_2_1_g307(.A (in2[11]), .B (inc_add_23_2_1_n_30),
       .Y (out1[11]));
  NAND2BX1 inc_add_23_2_1_g308(.AN (inc_add_23_2_1_n_54), .B (in2[30]),
       .Y (inc_add_23_2_1_n_60));
  XNOR2X1 inc_add_23_2_1_g309(.A (in2[28]), .B (inc_add_23_2_1_n_40),
       .Y (out1[28]));
  XNOR2X1 inc_add_23_2_1_g310(.A (in2[9]), .B (inc_add_23_2_1_n_1), .Y
       (out1[9]));
  XNOR2X1 inc_add_23_2_1_g311(.A (in2[7]), .B (inc_add_23_2_1_n_24), .Y
       (out1[7]));
  XNOR2X1 inc_add_23_2_1_g312(.A (in2[22]), .B (inc_add_23_2_1_n_44),
       .Y (out1[22]));
  XNOR2X1 inc_add_23_2_1_g313(.A (in2[26]), .B (inc_add_23_2_1_n_45),
       .Y (out1[26]));
  NAND2BX1 inc_add_23_2_1_g314(.AN (inc_add_23_2_1_n_45), .B (in2[26]),
       .Y (inc_add_23_2_1_n_53));
  NAND2BX1 inc_add_23_2_1_g315(.AN (inc_add_23_2_1_n_44), .B (in2[22]),
       .Y (inc_add_23_2_1_n_52));
  NAND2BX1 inc_add_23_2_1_g316(.AN (inc_add_23_2_1_n_40), .B (in2[28]),
       .Y (inc_add_23_2_1_n_51));
  NAND3BXL inc_add_23_2_1_g317(.AN (inc_add_23_2_1_n_40), .B (in2[29]),
       .C (in2[28]), .Y (inc_add_23_2_1_n_54));
  XOR2XL inc_add_23_2_1_g318(.A (in2[24]), .B (inc_add_23_2_1_n_29), .Y
       (out1[24]));
  XNOR2X1 inc_add_23_2_1_g319(.A (in2[14]), .B (inc_add_23_2_1_n_32),
       .Y (out1[14]));
  XNOR2X1 inc_add_23_2_1_g320(.A (in2[5]), .B (inc_add_23_2_1_n_20), .Y
       (out1[5]));
  XNOR2X1 inc_add_23_2_1_g321(.A (in2[20]), .B (inc_add_23_2_1_n_34),
       .Y (out1[20]));
  XNOR2X1 inc_add_23_2_1_g322(.A (in2[18]), .B (inc_add_23_2_1_n_33),
       .Y (out1[18]));
  NAND2BX1 inc_add_23_2_1_g323(.AN (inc_add_23_2_1_n_32), .B (in2[14]),
       .Y (inc_add_23_2_1_n_43));
  NAND2BX1 inc_add_23_2_1_g324(.AN (inc_add_23_2_1_n_33), .B (in2[18]),
       .Y (inc_add_23_2_1_n_42));
  NAND2BX1 inc_add_23_2_1_g325(.AN (inc_add_23_2_1_n_34), .B (in2[20]),
       .Y (inc_add_23_2_1_n_41));
  NAND2BX1 inc_add_23_2_1_g326(.AN (inc_add_23_2_1_n_4), .B
       (inc_add_23_2_1_n_29), .Y (inc_add_23_2_1_n_45));
  OR2XL inc_add_23_2_1_g327(.A (inc_add_23_2_1_n_7), .B
       (inc_add_23_2_1_n_34), .Y (inc_add_23_2_1_n_44));
  XNOR2X1 inc_add_23_2_1_g328(.A (in2[16]), .B (inc_add_23_2_1_n_23),
       .Y (out1[16]));
  XNOR2X1 inc_add_23_2_1_g329(.A (in2[3]), .B (inc_add_23_2_1_n_18), .Y
       (out1[3]));
  XOR2XL inc_add_23_2_1_g330(.A (in2[10]), .B (inc_add_23_2_1_n_25), .Y
       (out1[10]));
  XOR2XL inc_add_23_2_1_g331(.A (in2[12]), .B (inc_add_23_2_1_n_26), .Y
       (out1[12]));
  NAND2XL inc_add_23_2_1_g332(.A (in2[24]), .B (inc_add_23_2_1_n_29),
       .Y (inc_add_23_2_1_n_35));
  NAND4BX1 inc_add_23_2_1_g333(.AN (inc_add_23_2_1_n_4), .B
       (inc_add_23_2_1_n_29), .C (in2[27]), .D (in2[26]), .Y
       (inc_add_23_2_1_n_40));
  OR2XL inc_add_23_2_1_g334(.A (inc_add_23_2_1_n_14), .B
       (inc_add_23_2_1_n_23), .Y (inc_add_23_2_1_n_34));
  OR2XL inc_add_23_2_1_g335(.A (inc_add_23_2_1_n_5), .B
       (inc_add_23_2_1_n_23), .Y (inc_add_23_2_1_n_33));
  NAND2BX1 inc_add_23_2_1_g336(.AN (inc_add_23_2_1_n_11), .B
       (inc_add_23_2_1_n_26), .Y (inc_add_23_2_1_n_32));
  NAND2X1 inc_add_23_2_1_g338(.A (in2[12]), .B (inc_add_23_2_1_n_26),
       .Y (inc_add_23_2_1_n_31));
  NAND2X1 inc_add_23_2_1_g339(.A (in2[10]), .B (inc_add_23_2_1_n_25),
       .Y (inc_add_23_2_1_n_30));
  NOR4X1 inc_add_23_2_1_g340(.A (inc_add_23_2_1_n_23), .B
       (inc_add_23_2_1_n_14), .C (inc_add_23_2_1_n_6), .D
       (inc_add_23_2_1_n_7), .Y (inc_add_23_2_1_n_29));
  XNOR2X1 inc_add_23_2_1_g341(.A (in2[8]), .B (inc_add_23_2_1_n_0), .Y
       (out1[8]));
  XOR2XL inc_add_23_2_1_g342(.A (in2[6]), .B (inc_add_23_2_1_n_21), .Y
       (out1[6]));
  NOR2X1 inc_add_23_2_1_g343(.A (inc_add_23_2_1_n_13), .B
       (inc_add_23_2_1_n_0), .Y (inc_add_23_2_1_n_26));
  NOR2X1 inc_add_23_2_1_g344(.A (inc_add_23_2_1_n_9), .B
       (inc_add_23_2_1_n_0), .Y (inc_add_23_2_1_n_25));
  NAND2X1 inc_add_23_2_1_g346(.A (in2[6]), .B (inc_add_23_2_1_n_21), .Y
       (inc_add_23_2_1_n_24));
  OR4X1 inc_add_23_2_1_g348(.A (inc_add_23_2_1_n_0), .B
       (inc_add_23_2_1_n_13), .C (inc_add_23_2_1_n_10), .D
       (inc_add_23_2_1_n_11), .Y (inc_add_23_2_1_n_23));
  XNOR2X1 inc_add_23_2_1_g349(.A (in2[4]), .B (inc_add_23_2_1_n_17), .Y
       (out1[4]));
  NOR2X1 inc_add_23_2_1_g350(.A (inc_add_23_2_1_n_8), .B
       (inc_add_23_2_1_n_17), .Y (inc_add_23_2_1_n_21));
  NAND2BX1 inc_add_23_2_1_g351(.AN (inc_add_23_2_1_n_17), .B (in2[4]),
       .Y (inc_add_23_2_1_n_20));
  XNOR2X1 inc_add_23_2_1_g354(.A (in2[2]), .B (inc_add_23_2_1_n_15), .Y
       (out1[2]));
  NAND2BX1 inc_add_23_2_1_g355(.AN (inc_add_23_2_1_n_15), .B (in2[2]),
       .Y (inc_add_23_2_1_n_18));
  NAND3BXL inc_add_23_2_1_g357(.AN (inc_add_23_2_1_n_15), .B (in2[3]),
       .C (in2[2]), .Y (inc_add_23_2_1_n_17));
  XNOR2X1 inc_add_23_2_1_g358(.A (in2[1]), .B (inc_add_23_2_1_n_3), .Y
       (out1[1]));
  NAND2BX1 inc_add_23_2_1_g359(.AN (inc_add_23_2_1_n_3), .B (in2[1]),
       .Y (inc_add_23_2_1_n_15));
  NAND3BXL inc_add_23_2_1_g360(.AN (inc_add_23_2_1_n_5), .B (in2[19]),
       .C (in2[18]), .Y (inc_add_23_2_1_n_14));
  NAND3BXL inc_add_23_2_1_g361(.AN (inc_add_23_2_1_n_9), .B (in2[11]),
       .C (in2[10]), .Y (inc_add_23_2_1_n_13));
  XOR2XL inc_add_23_2_1_g362(.A (in2[0]), .B (in1), .Y (out1[0]));
  NAND2X1 inc_add_23_2_1_g363(.A (in2[13]), .B (in2[12]), .Y
       (inc_add_23_2_1_n_11));
  NAND2X1 inc_add_23_2_1_g364(.A (in2[15]), .B (in2[14]), .Y
       (inc_add_23_2_1_n_10));
  NAND2X1 inc_add_23_2_1_g365(.A (in2[9]), .B (in2[8]), .Y
       (inc_add_23_2_1_n_9));
  NAND2X1 inc_add_23_2_1_g366(.A (in2[5]), .B (in2[4]), .Y
       (inc_add_23_2_1_n_8));
  NAND2X1 inc_add_23_2_1_g367(.A (in2[21]), .B (in2[20]), .Y
       (inc_add_23_2_1_n_7));
  NAND2X1 inc_add_23_2_1_g368(.A (in2[23]), .B (in2[22]), .Y
       (inc_add_23_2_1_n_6));
  NAND2X1 inc_add_23_2_1_g369(.A (in2[17]), .B (in2[16]), .Y
       (inc_add_23_2_1_n_5));
  NAND2X1 inc_add_23_2_1_g370(.A (in2[25]), .B (in2[24]), .Y
       (inc_add_23_2_1_n_4));
  NAND2X1 inc_add_23_2_1_g371(.A (in2[0]), .B (in1), .Y
       (inc_add_23_2_1_n_3));
  NAND2BX1 inc_add_23_2_1_g2(.AN (inc_add_23_2_1_n_23), .B (in2[16]),
       .Y (inc_add_23_2_1_n_2));
  NAND2BX1 inc_add_23_2_1_g372(.AN (inc_add_23_2_1_n_0), .B (in2[8]),
       .Y (inc_add_23_2_1_n_1));
  NAND4BBXL inc_add_23_2_1_g373(.AN (inc_add_23_2_1_n_8), .BN
       (inc_add_23_2_1_n_17), .C (in2[7]), .D (in2[6]), .Y
       (inc_add_23_2_1_n_0));
endmodule


