`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 30 2023 21:44:50 CST (May 30 2023 13:44:50 UTC)

module SobelFilter_Add_5Ux1U_6U_1(in2, in1, out1);
  input [4:0] in2;
  input in1;
  output [5:0] out1;
  wire [4:0] in2;
  wire in1;
  wire [5:0] out1;
  wire inc_add_23_2_1_n_1, inc_add_23_2_1_n_2, inc_add_23_2_1_n_3,
       inc_add_23_2_1_n_4, inc_add_23_2_1_n_5, inc_add_23_2_1_n_6,
       inc_add_23_2_1_n_7, inc_add_23_2_1_n_9;
  wire inc_add_23_2_1_n_12, inc_add_23_2_1_n_13, n_30, n_31, n_32, n_34;
  MXI2X1 inc_add_23_2_1_g49(.A (inc_add_23_2_1_n_1), .B (in2[3]), .S0
       (inc_add_23_2_1_n_13), .Y (out1[3]));
  MXI2XL inc_add_23_2_1_g50(.A (inc_add_23_2_1_n_5), .B (in2[4]), .S0
       (inc_add_23_2_1_n_12), .Y (out1[4]));
  MXI2XL inc_add_23_2_1_g52(.A (inc_add_23_2_1_n_4), .B (in2[2]), .S0
       (n_31), .Y (out1[2]));
  NOR2X2 inc_add_23_2_1_g53(.A (inc_add_23_2_1_n_4), .B (n_32), .Y
       (inc_add_23_2_1_n_13));
  NOR2X2 inc_add_23_2_1_g55(.A (inc_add_23_2_1_n_7), .B (n_30), .Y
       (inc_add_23_2_1_n_12));
  MXI2XL inc_add_23_2_1_g57(.A (in2[1]), .B (inc_add_23_2_1_n_3), .S0
       (n_34), .Y (out1[1]));
  NOR2X2 inc_add_23_2_1_g58(.A (inc_add_23_2_1_n_3), .B
       (inc_add_23_2_1_n_6), .Y (inc_add_23_2_1_n_9));
  MXI2XL inc_add_23_2_1_g59(.A (inc_add_23_2_1_n_2), .B (in2[0]), .S0
       (in1), .Y (out1[0]));
  NAND2X1 inc_add_23_2_1_g60(.A (in2[3]), .B (in2[2]), .Y
       (inc_add_23_2_1_n_7));
  NAND2X8 inc_add_23_2_1_g61(.A (in2[0]), .B (in1), .Y
       (inc_add_23_2_1_n_6));
  INVX1 inc_add_23_2_1_g62(.A (in2[4]), .Y (inc_add_23_2_1_n_5));
  INVX1 inc_add_23_2_1_g63(.A (in2[2]), .Y (inc_add_23_2_1_n_4));
  INVX1 inc_add_23_2_1_g64(.A (in2[1]), .Y (inc_add_23_2_1_n_3));
  INVX1 inc_add_23_2_1_g65(.A (in2[0]), .Y (inc_add_23_2_1_n_2));
  INVXL inc_add_23_2_1_g66(.A (in2[3]), .Y (inc_add_23_2_1_n_1));
  NOR2BX1 inc_add_23_2_1_g2(.AN (inc_add_23_2_1_n_12), .B
       (inc_add_23_2_1_n_5), .Y (out1[5]));
  CLKINVX1 fopt70(.A (inc_add_23_2_1_n_9), .Y (n_30));
  INVXL fopt71(.A (n_32), .Y (n_31));
  CLKINVX1 fopt72(.A (inc_add_23_2_1_n_9), .Y (n_32));
  BUFX2 fopt(.A (inc_add_23_2_1_n_6), .Y (n_34));
endmodule


