`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 30 2023 22:08:14 CST (May 30 2023 14:08:14 UTC)

module SobelFilter_Subi1u5_4(in1, out1);
  input [4:0] in1;
  output [4:0] out1;
  wire [4:0] in1;
  wire [4:0] out1;
  wire dec_sub_21_2_1_n_0, dec_sub_21_2_1_n_2, dec_sub_21_2_1_n_3;
  INVX1 g3(.A (in1[0]), .Y (out1[0]));
  XNOR2X1 dec_sub_21_2_1_g44(.A (in1[3]), .B (dec_sub_21_2_1_n_3), .Y
       (out1[3]));
  XOR2XL dec_sub_21_2_1_g45(.A (in1[4]), .B (dec_sub_21_2_1_n_2), .Y
       (out1[4]));
  OAI2BB1X1 dec_sub_21_2_1_g46(.A0N (in1[2]), .A1N
       (dec_sub_21_2_1_n_0), .B0 (dec_sub_21_2_1_n_3), .Y (out1[2]));
  OR2XL dec_sub_21_2_1_g47(.A (in1[2]), .B (dec_sub_21_2_1_n_0), .Y
       (dec_sub_21_2_1_n_3));
  NOR3X1 dec_sub_21_2_1_g48(.A (dec_sub_21_2_1_n_0), .B (in1[3]), .C
       (in1[2]), .Y (dec_sub_21_2_1_n_2));
  OAI2BB1X1 dec_sub_21_2_1_g49(.A0N (in1[1]), .A1N (in1[0]), .B0
       (dec_sub_21_2_1_n_0), .Y (out1[1]));
  OR2X1 dec_sub_21_2_1_g50(.A (in1[1]), .B (in1[0]), .Y
       (dec_sub_21_2_1_n_0));
endmodule


